name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      version: 1.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Create patch
        env:
          VERSION: ${{ env.version }}
        run: ./create-patch.sh "$VERSION"

      - name: Check patch
        run: git diff --exit-code
        id: check-patch
        continue-on-error: true

      - name: Commit and push changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update patch
          name: Update Bot
          email: update@bot
          rebase: true
        if: steps.check-patch.outcome == 'failure'
