name: Check upstream
on:
  schedule:
    - cron: 0 0 * * 1

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - name: Fetch upstream
        run: |
          git remote add upstream git://git.suckless.org/slock
          git fetch --all

      - name: Check upstream
        run: git branch -a --merged | grep remotes/upstream/master > /dev/null 2>&1
